import 'package:flutter/material.dart';

class Game {
  final String gameImage,
      gameName,
      description,
      gameCate1,
      gameCate2,
      ageLimitImageForUser,
      price;
  final int sizeHeight, sizeWidth, id;
  // final Color color;
  Game({
    required this.gameImage,
    required this.gameName,
    required this.description,
    required this.gameCate1,
    required this.gameCate2,
    required this.ageLimitImageForUser,
    required this.price,
    required this.sizeHeight,
    required this.sizeWidth,
    required this.id,
    // required this.color,
  });
}

List<Game> game = [
  Game(
    gameImage: "assets/images/car.PNG",
    gameName: "롤링카",
    description: '롤링카 게임',
    gameCate1: '유아교육',
    gameCate2: '재활',
    ageLimitImageForUser: "assets/images/allRange.PNG",
    price: '₩2400',
    sizeHeight: 100,
    sizeWidth: 100,
    id: 1,
    // color: Color(0xFF3D82AE)),
  ),
  Game(
    gameImage: "assets/images/hotLap.PNG",
    gameName: "Hot Lap",
    description: '자동차 게임',
    gameCate1: '오락',
    gameCate2: '재활',
    ageLimitImageForUser: "assets/images/allRange.PNG",
    price: '₩2900',
    sizeHeight: 100,
    sizeWidth: 100,
    id: 1,
    // color: Color(0xFF3D82AE)),
  ),
  Game(
    gameImage: "assets/images/kidBall.PNG",
    gameName: "Kid Ball",
    description: '공 움직이기 게임',
    gameCate1: '유아교육',
    gameCate2: '치매',
    ageLimitImageForUser: "assets/images/allRange.PNG",
    price: '₩2400',
    sizeHeight: 100,
    sizeWidth: 100,
    id: 1,
    // color: Color(0xFF3D82AE)),
  ),
  Game(
    gameImage: "assets/images/paintColor.PNG",
    gameName: "성인 색칠",
    description: '색칠 게임',
    gameCate1: '성인',
    gameCate2: '치료',
    ageLimitImageForUser: "assets/images/allRange.PNG",
    price: '₩20400',
    sizeHeight: 100,
    sizeWidth: 100,
    id: 1,
    // color: Color(0xFF3D82AE)),
  ),
  Game(
    gameImage: "assets/images/thisBall.PNG",
    gameName: "this Ball",
    description: '공 튀기기 게임',
    gameCate1: '유아교육',
    gameCate2: '재활',
    ageLimitImageForUser: "assets/images/allRange.PNG",
    price: '₩2400',
    sizeHeight: 100,
    sizeWidth: 100,
    id: 1,
    // color: Color(0xFF3D82AE)),
  ),
  Game(
    gameImage: "assets/images/car.PNG",
    gameName: "롤링카",
    description: '롤링카 게임',
    gameCate1: '유아교육',
    gameCate2: '재활',
    ageLimitImageForUser: "assets/images/allRange.PNG",
    price: '₩2400',
    sizeHeight: 100,
    sizeWidth: 100,
    id: 1,
    // color: Color(0xFF3D82AE)),
  ),
  Game(
    gameImage: "assets/images/hotLap.PNG",
    gameName: "Hot Lap",
    description: '자동차 게임',
    gameCate1: '오락',
    gameCate2: '재활',
    ageLimitImageForUser: "assets/images/allRange.PNG",
    price: '₩2900',
    sizeHeight: 100,
    sizeWidth: 100,
    id: 1,
    // color: Color(0xFF3D82AE)),
  ),
  Game(
    gameImage: "assets/images/kidBall.PNG",
    gameName: "Kid Ball",
    description: '공 움직이기 게임',
    gameCate1: '유아교육',
    gameCate2: '치매',
    ageLimitImageForUser: "assets/images/allRange.PNG",
    price: '₩2400',
    sizeHeight: 100,
    sizeWidth: 100,
    id: 1,
    // color: Color(0xFF3D82AE)),
  ),
  Game(
    gameImage: "assets/images/paintColor.PNG",
    gameName: "성인 색칠",
    description: '색칠 게임',
    gameCate1: '성인',
    gameCate2: '치료',
    ageLimitImageForUser: "assets/images/allRange.PNG",
    price: '₩20400',
    sizeHeight: 100,
    sizeWidth: 100,
    id: 1,
    // color: Color(0xFF3D82AE)),
  ),
  Game(
    gameImage: "assets/images/thisBall.PNG",
    gameName: "this Ball",
    description: '공 튀기기 게임',
    gameCate1: '유아교육',
    gameCate2: '재활',
    ageLimitImageForUser: "assets/images/allRange.PNG",
    price: '₩2400',
    sizeHeight: 100,
    sizeWidth: 100,
    id: 1,
    // color: Color(0xFF3D82AE)),
  ),
  Game(
    gameImage: "assets/images/car.PNG",
    gameName: "롤링카",
    description: '롤링카 게임',
    gameCate1: '유아교육',
    gameCate2: '재활',
    ageLimitImageForUser: "assets/images/allRange.PNG",
    price: '₩2400',
    sizeHeight: 100,
    sizeWidth: 100,
    id: 1,
    // color: Color(0xFF3D82AE)),
  ),
  Game(
    gameImage: "assets/images/hotLap.PNG",
    gameName: "Hot Lap",
    description: '자동차 게임',
    gameCate1: '오락',
    gameCate2: '재활',
    ageLimitImageForUser: "assets/images/allRange.PNG",
    price: '₩2900',
    sizeHeight: 100,
    sizeWidth: 100,
    id: 1,
    // color: Color(0xFF3D82AE)),
  ),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";
